services:
  todo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo
    working_dir: /app
    command: go run ./cmd/todoapp
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - todo-postgres
    ports:
      - "8080:8080"

  todo-postgres:
    image: postgres:18.4-alpine
    container_name: postgresql_todo
    env_file:
      - .env
    volumes:
      - ${PROJECT_ROOT}/out/pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

  todo-migrate:
    image: migrate/migrate:v4.19.1
    env_file:
      - .env
    volumes:
      - ${PROJECT_ROOT}/migrations:/migrations
